# Async/Await

Pen√∫ltima entrega de Microbytes. Esta semana revisaremos un poco de ‚Äúaz√∫car sint√°ctica‚Äù. Async/Await .

La semana pasada revisamos que son las promesas y como trabajar con ellas, a modo de recordatorio

```javascript
const sleep = time => new Promise((resolve, reject) => setTimeout(resolve, time));

sleep(3000).then(() => {
	console.log('¬øFuncion√≥ la promesa?')
})
```

Esta funci√≥n `sleep` retorna una promesa, para ejecutar "algo" cuando la promesa es resuelta utilizamos `then` y pasamos una funci√≥n.

En modo general puedes considerar una funci√≥n que retorna una promesa como una funci√≥n as√≠ncrona. Pero, esto no es efectivamente declarado en el c√≥digo, si no m√°s bien inferido dado que la funci√≥n retorna una promesa. ¬øQu√© tal si tuvieras una manera de declarar que una promesa es as√≠ncrona?.

## Funciones as√≠ncronas.

> Como siempre, encuentra el [demo de este art√≠culo aqu√≠](https://jsitor.com/29TZ5Wnls4)

Una funci√≥n as√≠ncrona es aquella declarada utilizando la palabra clave `async`. Esta puede ser usada en funciones normales o en arrow functions.

```javascript
async function doSomething() {
}

const doSomething = async () => {
}
```

¬øQu√© significa esta declaraci√≥n `async`?

B√°sicamente lo que est√°s haciendo es indic√°ndole al int√©rprete que la funci√≥n `doSomething` retornar√° **siempre** una promesa.

```javascript
const doSomething = async () => {
	return 1
}

// es lo mismo

const doSomething = () => new Promise(resolve => resolve(1))

// ambas se usan igual

const promise = doSomething()
promise.then(result => {
	console.log(reuslt)
})
```

Pero, a pesar de ser sem√°nticamente lo mismo para el interprete el uso de `async` nos ofrece una nueva caracter√≠stica

## `await`

El uso de `async` para declarar tu funci√≥n te permite usar una nueva palabra clave: `await` que de forma muy resumida, te permite literalmente esperar a que la promesa est√© resuelta.

```javascript
// sin async/await
const getData = () => {
  console.log('Fetching...')
  fetchData().then(result => {
	// hacer algo con el resultado
	console.log(result)
	return result
  })
}

// usando async/await

const asyncGetData = async () => {
  console.log('Fetching async....')
  const result = await fetchData()
  console.log(result)
}
```

En el ejemplo tenemos la misma implementaci√≥n, primer con promesa y luego con `async/await` la diferencia es clara, el uso de `await` permite una mejor legibilidad. B√°sicamente, `await` es un reemplazo del c√≥digo que escribes dentro de la llamada a `then` en una promesa y te permite escribir c√≥digo de forma s√≠ncrona.

Pero, tu bien sabes que una promesa puede ser resuelta o rechazada y notaste que `await` solo determina el camino feliz de una promesa resuelta con √©xito. ¬øQue ocurre con los errores?.

## Manejo de errores

El objeto Promise nos ofrece 3 m√©todos que te permiten controlar el flujo de la promesa o ‚Äúsuscribirte a los cambios de estado‚Äù, estos son `then`, `catch` y `finally`.

`then` se ejecuta en caso de una promesa exitosa y es lo que conseguimos al utilizar `await`.

`catch` define el trozo de c√≥digo que se ejecutar√° si la promesa fue rechazada, es decir, tu manejo de errores. En el caso de `async/await` no tenemos la misma definici√≥n pero, podemos decantar al nunca bien ponderado bloque `try

`catch` define el trozo de c√≥digo que se ejecutar√° si la promesa fue rechazada, es decir, tu manejo de errores. En el caso de `async/await` no tenemos la misma definici√≥n pero, podemos decantar al nunca bien ponderado bloque `try/catch`

```javascript
const asyncGetDataWithTry = async () => {
  console.log('Fetching async....')
  try {
	const result = await fetchData()
	console.log('Async Data: ', result)
  }catch(e) {
	console.log(e)
  }  
}
```

El proceso completo de la promesa se ejecuta dentro del bloque `try` y si esta promesa llegase a falla, el bloque `catch` se encarga de ella.

El bloque `finally` es lo que puedes escribir directamente fuera del bloque `try/catch.`

Ahora, ¬øqu√© ocurre si tienes varias promesas y varios bloque `try/catch` ?

```javascript
const test = async () => {
  try {
	const one = await getOne(false)
  } catch (error) {
	console.log(error)
  }

  try {
	const two = await getTwo(true)
  } catch (error) {
	console.log(error)
  }

  try {
	const three = await getThree(false)
  } catch (error) {
	console.log(error)
  }
}
```

Eso no se ve nada bien.

¬øQu√© puedes hacer?

Una forma de mejorar la legibilidad de esto es simplemente poner todo dentro de un s√≥lo bloque `try/catch`

```javascript
const test = async () => {
  try {
	const one = await getOne(false)
	const two = await getTwo(false)
	const three = await getThree(false)
  }catch (error) {
	console.log(error) // Failure!
  }
}
```

idealmente el objeto error retornado por las promesas tiene alg√∫n c√≥digo identificador lo que te permite identificar cual fue el error.

> ¬øDe que otra forma puedes escribir el manejo de errores de m√∫ltiples funciones as√≠ncronas?
Cu√©ntame tu soluci√≥n respondiendo a este email o en un tweet üòé

# Conclusi√≥n

En resumen `async/await` es una notaci√≥n o sintaxis que busca simplificar el proceso de escribir (y sobre todo leer y mantener) c√≥digo as√≠ncrono transformado el uso de promesas y callbacks en c√≥digo que se puede seguir de forma s√≠ncrona, para esto `await` espera por el resultado de la promesa deteniendo la ejecuci√≥n hasta que la promesa se resuelva - el c√≥digo justo despu√©s de `await` no se ejecuta hasta que la promesa est√© lista - .

> No olvides que no puedes usar `await` si no has declarado la funci√≥n como as√≠ncrona utilizando `async`.

# Desaf√≠o

Imagina que tienes que ejecutar m√∫ltiples llamadas as√≠ncronas a una API externa, cada llamada a la API demora casi 1 segundo.

```javascript
const test = async _ => {
  const one = await fetchOne()
  console.log(one)

  const two = await fetchTwo()
  console.log(two)

  const three = await fetchThree()
  console.log(three)

  console.log('Done')
}
```

Este c√≥digo resuelve el problema pero crea otro: Cada llamada espera que la anterior termine, y si cada llamada demora 1 segundo, entonces el proceso estar√° listo solo despu√©s de 3 segundos!!.

Y por lo que este c√≥digo muestra, las llamadas no son dependientes entre si. 
¬øC√≥mo puedes escribir este c√≥digo pero ejecutando las 3 llamadas en paralelo?

Pista: El objeto `Promise` tiene un m√©todo que te permitir√° resolver este problema.

